### ISSUE TITLE
Make game

### ISSUE THREAD

**Issue by squidink7** [Joltemon/GameProduction#1]
### Describe the bug:

Right now there is no game

### What do you expect to happen?:

There should be a game

### Possible solution:

Make game

### Steps to reproduce:

Download repository
Open in Godot
Stare into the emptiness

**Comment by Dragons788** [comment]
no.

**Comment by Joltemon** [comment]
![image](https://user-images.githubusercontent.com/113022918/231395774-48f25cbd-f208-4ac5-b3c9-4b55e9866f6b.png)
